Список сообщений<br><br>
<?php
/** @var $messages \App\Model\Message */

/** @var $user \App\Model\User */
$user = $this->user; ?>
<?php
if ($messages = $this->messages): ?>
<?php
foreach ($messages

as $message): ?>
<div>
    <?php
    if ($author = $message->getUser()): ?>
        <div> <?= htmlspecialchars($author->getEmail()) ?></div>
    <?php
    else: ?>
        <div> Сообщение от удаленного пользователя</div>
    <?php
    endif; ?>
    <?= $message->getCreatedAt() ?> <?= htmlspecialchars(nl2br($message->getText())) ?>
    <br>
    <?php
    if ($message->getImage()): ?>
        <div>
            <img src="../images/<?= $message->getImage(); ?>" width="150"
                 height="90">
        </div>
    <?php
    endif; ?>
    <?php
    if ($user->isAdmin()): ?>
        <div>
            <a href="/new-school/task5/html/admin/deleteMessage/?id=<?= $message->getId(); ?>">delete</a>
        </div>
    <?php
    endif; ?> <br><br>
    <?php
    endforeach; ?>
    <?php
    else: ?>
        Сообщений пока нет
    <?php
    endif; ?>
    Добавить сообщение:
    <br>
    <form enctype="multipart/form-data"
          action="/new-school/task5/html/blog/addMessage" method="post">
        Текст: <textarea type="text" name="text"></textarea><br><br>
        Загрузить изображение:<br>
        <input type="file" name="images"><br><br>
        <input type="submit" value="Отправить">
    </form>

    <br>
    <form action="/new-school/task5/html/user/logout">
        <input type="submit" value="Выйти">
    </form>
