Регистрация:
<form action="/new-school/task5/html/user/register" method="post">
    Имя: <input type="text" name="name"><br>
    Email: <input type="email" name="email"><br>
    Пароль: <input type="password" name="password1"><br>
    Повторите пароль: <input type="password" name="password2"><br>
    <input type="submit" value="Зарегистрироваться">
</form>
<br>
<br>

Войти:
<form action="/new-school/task5/html/user/login" method="post">
    E-mail: <input type="text" name="email"><br>
    Пароль: <input type="password" name="password"><br>
    <input type="submit" value="Войти">
</form>

<br>
<br>
<?php
if ($this->error): ?>
    <span style="color: red"> <?= $this->error; ?> </span>
<?php
endif; ?>
